export const EMPTY = []

export const SMALL = [
  {
    id: "1",
    title: "Burger Meal",
    imageSource: "/images/burger1.webp",
    quantity: 1,
  },
]

export const MEDIUM = [
  {
    id: "1",
    imageSource: "/images/burger-bacon-egg.webp",
    title: "Burger Smoke BBQ",
    price: 5,
    quantity: 2,
  },
  {
    id: "2",
    imageSource: "/images/burger-vegan.webp",
    title: "Vegan Burger",
    price: 5,
    quantity: 1,
  },
  {
    id: "3",
    imageSource: "/images/burger1.webp",
    title: "Burger House",
    price: 5,
    quantity: 4,
  },
  {
    id: "4",
    imageSource: "/images/burger2.webp",
    title: "Cheese Burger",
    price: 5,
    quantity: 4,
  },
]

export const LARGE = [
  {
    id: "1",
    imageSource: "",
    title: "New Burger",
    price: 3.1678,
    quantity: 13,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "2",
    imageSource: "/images/drink1.webp",
    title: "Coke 25cl",
    price: 3.568,
    quantity: 1,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "3",
    imageSource: "/images/burger3.webp",
    title: "Burger poulet",
    price: 5.367,
    quantity: 5,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "4",
    imageSource: "/images/burger-vegan.webp",
    title: "Vegan Burger",
    price: 5.4985,
    quantity: 1,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "5",
    imageSource: "/images/drink2.webp",
    title: "Pepsi 25cl",
    price: 3.487,
    quantity: 1,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "6",
    imageSource: "/images/drink3.webp",
    title: "Iced Tea 25cl",
    price: 3.356,
    quantity: 1,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "7",
    imageSource: "/images/burger-bacon-egg.webp",
    title: "Burger Smoke Bdhbedhbeheb",
    price: 5.598,
    quantity: 1,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "8",
    imageSource: "/images/frites1.webp",
    title: "Frites Paprika",
    price: 2.567,
    quantity: 1,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "9",
    imageSource: "/images/wedges1.webp",
    title: "Crispy Potatoes",
    price: 3.7,
    quantity: 1,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "10",
    imageSource: "/images/ice-cream.webp",
    title: "Glaces artisanales",
    price: 4.678,
    quantity: 1,
    isAvailable: true,
    isAdvertised: false,
  },
]

export const LARGE_WEIRD = [
  {
    id: "1",
    imageSource: "/images/fries3.webp",
    title: "New York Fries",
    price: 3.1678,
    quantity: 13,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "2",
    imageSource: "/images/drink1.webp",
    title: "Coke 25cl",
    price: 3.568,
    quantity: 1,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "3",
    imageSource: "/images/burger3.webp",
    title: "Burger poulet chanmé",
    price: 0.0,
    quantity: 5,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "4",
    imageSource: "/images/burger-vegan.webp",
    title: "Vegan Burger",
    price: 5.4985,
    quantity: 1,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "5",
    imageSource: "/images/drink2.webp",
    title: "Pepsi 25cl MEGA OUF XXXL",
    price: 3.487,
    quantity: 1,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "6",
    imageSource: "/images/drink3.webp",
    title: "",
    price: 3.356,
    quantity: 1,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "7",
    imageSource: "/images/burger-bacon-egg.webp",
    title: "Burger Smoke Bdhbedhbeheb",
    price: 5.598,
    quantity: 1,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "8",
    imageSource: "/images/frites1.webp",
    title: "Frites Paprika",
    price: 2.567,
    quantity: 1,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "9",
    imageSource: "/images/wedges1.webp",
    title: "Crispy Potatoes",
    price: 3.7,
    quantity: 1,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: "10",
    imageSource: "/images/ice-cream.webp",
    title: "Glaces artisanales",
    price: 4.678,
    quantity: 1,
    isAvailable: true,
    isAdvertised: false,
  },
]

export const fakeBasket = {
  EMPTY,
  SMALL,
  MEDIUM,
  LARGE,
  LARGE_WEIRD,
}
